#! /usr/bin/env python

import os
import json
from random import randrange
from datetime import datetime
from relayr.client import Client
from relayr.resources import Device

TOKEN=os.getenv("TOKEN")

if TOKEN is None:
    raise Exception("Please set the environment variable TOKEN.")

DEVICE_ID="0f637589-6fea-47b8-867f-bbab4aafcf79"

print("OAuth Token: %s" % TOKEN)

client = Client(token=TOKEN)
device = Device(DEVICE_ID, client)
for i in range(100):
    iso = datetime.now().isoformat()

    # any python dictionary will be ok here
    command = { "speed" : randrange(0, 100), "sent" : iso }
    device.send_command(command)
    jsonstr = json.dumps(command)
    print("Sending command %s" % jsonstr)
