#! /usr/bin/env python

import os
import json
from random import randrange
from datetime import datetime
from config import *
from relayr.client import Client
from relayr.resources import Device

print("OAuth Token: %s" % TOKEN)

client = Client(token=TOKEN)
device = Device(DEVICE_ID, client)
for i in range(100):
    iso = datetime.now().isoformat()

    # any python dictionary will be ok here
    command = { "speed" : randrange(0, 100), "sent" : iso }
    device.send_command(command)
    jsonstr = json.dumps(command)
    print("Sending command %s" % jsonstr)
